# -*- coding: utf-8 -*-
"""Calculadora basica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IIoB6eUS954Snep1kQjGlJfddunoTzl2

CALCULADORA BASICA
"""

def somar(a, b):
    return a + b

def subtrair(a, b):
    return a - b

def multiplicar(a, b):
    return a * b

def dividir(a, b):
    if b == 0:
        return "Erro: divisão por zero"
    return a / b

print("Calculadora Básica")
print("Operações: +, -, *, /")

a = float(input("Digite o primeiro número: "))
op = input("Digite a operação: ")
b = float(input("Digite o segundo número: "))

if op == "+":
    print("Resultado:", somar(a, b))
elif op == "-":
    print("Resultado:", subtrair(a, b))
elif op == "*":
    print("Resultado:", multiplicar(a, b))
elif op == "/":
    print("Resultado:", dividir(a, b))
else:
    print("Operação inválida")